esphome:
  name: garo-reader
  friendly_name: garo-reader

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

uart:
  id: mod_bus
  tx_pin: GPIO00
  rx_pin: GPIO01
  baud_rate: 9600
  stop_bits: 1
  parity: NONE
  rx_buffer_size: 256
  data_bits: 8

modbus:
  #flow_control_pin: 5
  id: modbus1

modbus_controller:
  - id: garobus
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    offline_skip_updates: 3
    update_interval: 10s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key goes here"

ota:
  password: "pw goes here"

sensor:
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'V' 
    name: "Voltage Phase 1"
    id: f1_v
    register_type: holding
    value_type: S_DWORD_R
    address: 0x0000
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'V' 
    name: "Voltage Phase 2"
    id: f2_v
    register_type: holding
    value_type: S_DWORD_R
    address: 0x0002
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    unit_of_measurement: 'V' 
    modbus_controller_id: garobus
    name: "Voltage Phase 3"
    id: f3_v
    register_type: holding
    value_type: S_DWORD_R
    address: 0x0004
    accuracy_decimals: 1
    register_count: 8
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'A' 
    name: "Current Phase 1"
    id: f1_a
    register_type: holding
    value_type: S_DWORD_R
    address: 0x000C
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'A' 
    name: "Current Phase 2"
    id: f2_a
    register_type: holding
    value_type: S_DWORD_R
    address: 0x000E
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'A' 
    name: "Current Phase 3"
    id: f3_a
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 3
    address: 0x0010
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'W' 
    name: "Power Consumed Phase 1"
    id: f1_kw
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0012
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'W' 
    name: "Power Consumed Phase 2"
    id: f2_kw
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0014
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'W' 
    name: "Power Consumed Phase 3"
    id: f3_kw
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0016
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'W' 
    name: "Power Consumed System"
    id: kw_sys
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0106
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'Hz' 
    name: "Frequenzy"
    id: hz
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0110
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'kWh' 
    name: "Energy Consumed Total"
    state_class: total_increasing
    id: kwh_tot
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0112
    register_count: 6
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'W' 
    name: "Power Consumed Demand"
    id: kw_dmd
    register_type: holding
    value_type: S_DWORD_R
    address: 0x011A
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'W' 
    name: "Power Consumed Demand Peak"
    id: kw_dmd_peak
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x011C
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'kWh' 
    name: "Energy Consumed Partial"
    id: kwh_partial
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0148
    register_count: 4
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'kWh' 
    name: "Energy Consumed Phase 1"
    id: f1_kwh
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x014C
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'kWh' 
    name: "Energy Consumed Phase 2"
    id: f2_kwh
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x014E
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: garobus
    unit_of_measurement: 'kWh' 
    name: "Energy Consumed Phase 3"
    id: f3_kwh
    register_type: holding
    value_type: S_DWORD_R
    accuracy_decimals: 1
    address: 0x0150
    filters:
      - multiply: 0.1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
